version: "3.7"

services:
  #nginx
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./sites-enabled:/etc/nginx/sites-enabled
  # nginx-proxy-acme:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./vhost:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html
  #     - ./acme:/etc/acme.sh
  #   environment:
  #     - DEFAULT_EMAIL=<your email>
  #   volumes_from:
  #     - nginx-proxy

  #redis
  redis:
    image: redis:6.2.6-alpine
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  frontend:
    container_name: closedai-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    # ports:
    #   - '3000:80'
    restart: always
    # environment:
    #   - VIRTUAL_HOST=<your domain>
    #   - LETSENCRYPT_HOST=<your domain>
    # expose:
    #   - 80

  backend:
    container_name: closedai-backend
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - '5000:5000'
    volumes:
      - ./prisma:/usr/src/app/prisma
    depends_on:
      - redis
    restart: always
    environment:
      - VIRTUAL_HOST=api.<your domain>
      - LETSENCRYPT_HOST=api.<your domain>
    expose:
      - 5000
